config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  root  "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user

	has_many :ingredients
	has_many :directions

	accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

	validates :title, :description, :image, presence: true
	
	has_attached_file :image, styles: { :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show
	end

	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)

		if @recipe.save
			redirect_to @recipe, notice: "Succesfully created new recipe"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Succesfully deleted recipe"
	end

	private

	def recipe_params
		params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!!5
%html
%head
  %title Marmita
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Marmita", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Recipe", new_recipe_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path

  .container
    -flash.each do |name, msg|
      =content_tag :div, msg, class: "alert"

    = yield

app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :step, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove step", f, class: "form-button btn btn-default"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
	- if @recipe.errors.any?
		#errors
			%p
				= @recipe.errors.count
				Prevented this recipe froms saving
			%ul
				- @recipe.errors.full_messages.each do |msg|
					%li= msg
	.panel_body
		=f.input :title, input_html: { class: 'form-control' }
		=f.input :description, input_html: { class: 'form-control' }
		=f.input :image, input_html: { class: 'form-control' }

		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association 'Add ingredient', f, :ingredients, class: "btn btn-default add-button"
			.col-md-6
				%h3 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f: direction
					.links
						= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button"

	= f.button :submit, class: "btn btn-primary"

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: "form-input form-control" }
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

app/views/recipes/index.html.haml
- @recipe.each_slice(3) do |recipes|
	.row
		- recipes.each do |recipe|
			.col-md-4
				.recipe
					.image_wrapper
						= link_to recipe do
							= image_tag recipe.image.url(:medium)
					%h2= link_to recipe.title, recipe

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/show.html.haml
.main_content
	#recipe_top.row
		.col-md-4
			= image_tag @recipe.image.url(:medium), class: "recipe_image"
		.col-md-8
			#recipe_info
				%h1= @recipe.title
				%p.descripition= @recipe.description
				%p 
					Submitted by
					= @recipe.user.email

	.row
		.col-md-6
			#ingredients
				%h2 Ingredients
				%ul
					- @recipe.ingredients.each do |ingredient|
						%li= ingredient.name

		.col-md-6
			#directions
				%h2 Directions
				%ul
					- @recipe.directions.each do |direction|
						%li= direction.step

	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-default"
			- if user_signed_in?
				= link_to "Edit", edit_recipe_path, class: "btn btn-default"
				= link_to "Delete", recipe_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"